[user]
name = "John Doe"
address = "123 Anywhere St, City, Country"
invoice_number = "INV-2023-0001"
pan = "ABCDE1234F"
gst = "27ABCDE1234F1Z5"

[user.bank]
account_name = "John Doe"
account_number = "1234567890"
bank_name = "Some Bank"
branch = "Some Branch"
ifsc = "SBIN0000001"
address = "Bank Address, City, Country"

[company]
name = "XYZ P:wqvt Ltd"
address = "456 Anywhere St, City, Country"
contact_person = "Jane Doe"
contact_number = "+1234567890"
contact_email = "contact@xyz.com"
gst_number = "27ABCDE1234F1Z5"

[[items]]
description = "Designing a website"
sac_code = "998311"
hourly_cost = 30
hours = 5
amount = 0

[[items]]
description = "Creating a logo"
sac_code = "998312"
hourly_cost = 40
hours = 3
amount = 0